agregar archivo deploy v5

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,13 +47,17 @@ jobs:
           port: 5356
           debug: true
           script: |
-            echo "Current directory: $(pwd)"
-            echo "Listing directory contents:"
-            ls -la
-            echo "Checking SSH directory:"
-            ls -la ~/.ssh
-            echo "Checking authorized_keys:"
-            cat ~/.ssh/authorized_keys
+            echo "Installing Docker Compose if not present..."
+            if ! command -v docker-compose &> /dev/null; then
+              echo "Docker Compose not found. Installing..."
+              curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+              chmod +x /usr/local/bin/docker-compose
+              ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
+            fi
+            
+            echo "Verifying Docker Compose installation..."
+            docker-compose --version
+            
             echo "Deploying application..."
             cd ~/portfolio-react
             docker pull ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-react:latest
